spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/hackathon}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:qpwoeiru1768}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always
